[package]
name = "zimler-midi"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
midir = { workspace = true }
crossbeam = { workspace = true }