name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        targets: ${{ matrix.target }}
    
    # Use make commands for consistency
    - name: Lint
      run: make lint
    
    - name: Test
      run: make test
    
    - name: Build Release
      run: cargo build --release --target ${{ matrix.target }} -p zimler-desktop
    
    - name: Package
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp target/${{ matrix.target }}/release/zimler.exe zimler-${{ matrix.target }}.exe
        else
          cp target/${{ matrix.target }}/release/zimler zimler-${{ matrix.target }}
        fi
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: zimler-${{ matrix.target }}*